# Generated by Django 3.2.8 on 2021-11-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiMuon',
            fields=[
                ('ten', models.CharField(max_length=200)),
                ('masv', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(default=None, max_length=100)),
                ('namSinh', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('token', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('maSach', models.IntegerField(primary_key=True, serialize=False)),
                ('tenSach', models.CharField(max_length=200)),
                ('tacGia', models.CharField(max_length=200)),
                ('theLoai', models.CharField(max_length=100)),
                ('ngonNgu', models.CharField(max_length=100)),
                ('soLuong', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TheMuon',
            fields=[
                ('maThe', models.AutoField(primary_key=True, serialize=False)),
                ('ngayMuon', models.DateField()),
                ('ngayTra', models.DateField()),
                ('soLuong', models.IntegerField(default=0)),
                ('nguoiMuon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvien.nguoimuon')),
            ],
        ),
        migrations.CreateModel(
            name='TheMuon_Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvien.sach')),
                ('themuon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvien.themuon')),
            ],
        ),
    ]
