# Generated by Django 3.2.8 on 2021-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thuvien', '0002_alter_themuon_mathe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themuon',
            name='soLuong',
        ),
        migrations.AddField(
            model_name='themuon_sach',
            name='soLuong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='themuon',
            name='ngayMuon',
            field=models.DateField(auto_now_add=True),
        ),
    ]
