# Generated by Django 3.2.8 on 2021-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thuvien', '0003_auto_20211107_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoimuon',
            name='token',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
